import LineChart from "@/components/LineChart";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import Widgets from "@/components/Widgets";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Listed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-primary-bg">
        <div className="flex p-6 gap-2 md:min-w-fit">
          <div>
            <Sidebar />
          </div>

          <div className="flex-1 bg-transparent">
            <div className="flex flex-col h-full">
              <div>
                <Navbar />
              </div>
              <div className="flex flex-wrap gap-10 p-8 md:justify-center">
                <Widgets type={"revenue"} />
                <Widgets type={"transaction"} />
                <Widgets type={"likes"} />
                <Widgets type={"users"} />
              </div>
              <div className=" py-3 px-7">
                <LineChart />
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
