import Navbar from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'
import Widgets from "@/components/Widgets";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Listed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex p-6 bg-primary-bg gap-2 md:min-w-fit">
        <div>
          <Sidebar />
        </div>

        <div className="flex-1 bg-transparent">
          <div className="flex flex-col">
            <div>
              <Navbar />
            </div>
            <div className="flex p-20 gap-20 md:flex-wrap md:gap-10">
              <Widgets type={"revenue"} />
              <Widgets type={"transaction"} />
              <Widgets type={"likes"} />
              <Widgets type={"users"} />
            </div>
            <div className="flex py-5 px-20 gap-20">charts</div>
          </div>
        </div>
      </div>
    </>
  );
}
