import LineChart from "@/components/LineChart";
import Navbar from "@/components/Navbar";
import PieChart from "@/components/PieChart";
import Schedule from "@/components/Schedule";
import Sidebar from "@/components/Sidebar";
import Widgets from "@/components/Widgets";
import Head from "next/head";
import { getSession, useSession, signOut } from "next-auth/react";
import Login from "./login";

export default function Home() {
  const { data: session } = useSession();

  function handleSignOut() {
    signOut();
  }
  return (
    <div>
      <Head>
        <title>Listed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? (
        <div className="bg-primary-bg">
          <div className="flex p-6 gap-2 md:min-w-fit">
            <div>
              <Sidebar />
            </div>

            <div className="flex-1 bg-transparent">
              <div className="flex flex-col h-full sm:flex-wrap">
                <div>
                  <Navbar />
                  <div
                    onClick={handleSignOut}
                    className="text-red-900 font-black cursor-pointer"
                  >
                    sign out
                  </div>
                </div>
                <div className="flex flex-wrap gap-10 p-8 md:justify-center">
                  <Widgets type={"revenue"} />
                  <Widgets type={"transaction"} />
                  <Widgets type={"likes"} />
                  <Widgets type={"users"} />
                </div>
                <div className=" py-3 px-7">
                  <LineChart />
                </div>
                <div className="flex sm:flex-wrap gap-3">
                  <PieChart />
                  <Schedule />
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <Login />
      )}
    </div>
  );
}

export async function getServerSideProps({ req }) {
  const session = await getSession({ req });

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}